TestMyHammingCode.out: TestMyHammingCode.o MyHammingCode.o
	g++ -o TestMyHammingCode.out TestMyHammingCode.o MyHammingCode.o

TestMyHammingCode.o: MyHammingCode.h TestMyHammingCode.cpp
MyHammingCode.o: MyHammingCode.h MyHammingCode.cpp 
