TestMyHammingCode.out: TestMyHammingDistance.o MyHammingDistance.o
	g++ -o TestMyHammingDistance.out TestMyHammingDistance.o MyHammingDistance.o

TestMyHammingDistance.o: MyHammingDistance.h TestMyHammingDistance.cpp
MyHammingDistance.o: MyHammingDistance.h MyHammingDistance.cpp 
